/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as QrRouteImport } from './routes/qr'
import { Route as JuicesRouteImport } from './routes/juices'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JuicesIndexRouteImport } from './routes/juices.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as JuicesIdRouteImport } from './routes/juices.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const JuicesRoute = JuicesRouteImport.update({
  id: '/juices',
  path: '/juices',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuicesIndexRoute = JuicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JuicesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const JuicesIdRoute = JuicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JuicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/juices': typeof JuicesRouteWithChildren
  '/qr': typeof QrRoute
  '/shop': typeof ShopRoute
  '/subscription': typeof SubscriptionRoute
  '/track': typeof TrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/juices/$id': typeof JuicesIdRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/blog/': typeof BlogIndexRoute
  '/juices/': typeof JuicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/qr': typeof QrRoute
  '/shop': typeof ShopRoute
  '/subscription': typeof SubscriptionRoute
  '/track': typeof TrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/juices/$id': typeof JuicesIdRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/blog': typeof BlogIndexRoute
  '/juices': typeof JuicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/juices': typeof JuicesRouteWithChildren
  '/qr': typeof QrRoute
  '/shop': typeof ShopRoute
  '/subscription': typeof SubscriptionRoute
  '/track': typeof TrackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/juices/$id': typeof JuicesIdRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/blog/': typeof BlogIndexRoute
  '/juices/': typeof JuicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/juices'
    | '/qr'
    | '/shop'
    | '/subscription'
    | '/track'
    | '/blog/$slug'
    | '/juices/$id'
    | '/order/$orderNumber'
    | '/blog/'
    | '/juices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/qr'
    | '/shop'
    | '/subscription'
    | '/track'
    | '/blog/$slug'
    | '/juices/$id'
    | '/order/$orderNumber'
    | '/blog'
    | '/juices'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/juices'
    | '/qr'
    | '/shop'
    | '/subscription'
    | '/track'
    | '/blog/$slug'
    | '/juices/$id'
    | '/order/$orderNumber'
    | '/blog/'
    | '/juices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  JuicesRoute: typeof JuicesRouteWithChildren
  QrRoute: typeof QrRoute
  ShopRoute: typeof ShopRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TrackRoute: typeof TrackRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juices': {
      id: '/juices'
      path: '/juices'
      fullPath: '/juices'
      preLoaderRoute: typeof JuicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juices/': {
      id: '/juices/'
      path: '/'
      fullPath: '/juices/'
      preLoaderRoute: typeof JuicesIndexRouteImport
      parentRoute: typeof JuicesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juices/$id': {
      id: '/juices/$id'
      path: '/$id'
      fullPath: '/juices/$id'
      preLoaderRoute: typeof JuicesIdRouteImport
      parentRoute: typeof JuicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface JuicesRouteChildren {
  JuicesIdRoute: typeof JuicesIdRoute
  JuicesIndexRoute: typeof JuicesIndexRoute
}

const JuicesRouteChildren: JuicesRouteChildren = {
  JuicesIdRoute: JuicesIdRoute,
  JuicesIndexRoute: JuicesIndexRoute,
}

const JuicesRouteWithChildren =
  JuicesRoute._addFileChildren(JuicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  JuicesRoute: JuicesRouteWithChildren,
  QrRoute: QrRoute,
  ShopRoute: ShopRoute,
  SubscriptionRoute: SubscriptionRoute,
  TrackRoute: TrackRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
